name: tigerbook
description: "DAM project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The version number is three parts:
version: 1.0.0+1

# The following section is specific to Flutter.
environment:
  sdk: '>=3.3.4 <4.0.0'

# The following line is for dependencies. Dependencies are external packages
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.17.3
  uuid: ^4.4.0
  image_picker: ^1.1.1
  future_progress_dialog: ^0.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_launcher_icons: ^0.13.1

# The following dev_dependencies section is for packages that are only needed during development.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following sections is for configuration of the app.
flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"

# The following line specifies the Flutter SDK that the app uses.
flutter:
  uses-material-design: true
